# Generated by Django 4.2.6 on 2023-10-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ssavi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedTrack',
            fields=[
                ('lt_no', models.IntegerField(db_column='LT_no', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'liked_track',
                'managed': False,
            },
        ),
    ]
